### ISSUE TITLE
Semantic web

### ISSUE THREAD

**Issue by echo66** [acutesoftware/AIKIF#20]
Did you take a look at semantic web standards and tech? Most of your design goals are met by those standards and technologies.

**Comment by acutesoftware** [comment]
Thanks for your comment - yes I spent a fair amount of time trying out the tools and trying to work out which ontology to use (found over 20 upper ontologies at the time - http://www.acutesoftware.com.au/aikif/ontology.html - and decided to focus on openCyc and/or WordNet. Would be interested if you have other thoughts on that? Or a better ontology to use?

(One of) the intentions of this project is not to replace those ontologies, but to use them by mapping users data and processes to them in a simple way. I'm still not entirely sure this will pan out as that part is a work in progress.

**Comment by echo66** [comment]
The choice of an upper ontology is a different manter than choosing to use semantic web technologies.

Do you have any guidelines that helped you determine what ontology you needed?

Got to sleep. See you later. :)

**Comment by acutesoftware** [comment]
Do you have any examples of a semantic web technology I could try? I am not entirely sure a web api would work in this project as it deals with a lot of local user data, and wouldn't want to make a web service call for each data item or even table.  Be interesting to try though - nothing is set in stone.
 
Hope I am not completely missing your point here. Let me know :)

**Comment by echo66** [comment]
Even if you are dealing with local (produced) data, having standard and well defined semantics (like OWL or First Order Logic) would help a lot because there are many reasoners that can manipulate such datasets (Pellet, Hermit, FaCT++, RDFox, etc). You can even integrate data from the Linked Data cloud without any need for complex ETL.

What kind of domains do you envision that AIKIF can be used?

Don't be afraid to be deeply technical in subjects like Knowledge Representation & Reasoning, Knowledge Engineering & Management because my master thesis belongs to those very same subjects.

PS.: I found out about your project in Hacker News. :+1:

**Comment by acutesoftware** [comment]
Those reasoning tools look interesting - I didnt come across them when I first looked at this.

> What kind of domains do you envision that AIKIF can be used?

Personal Information Management
Events, contacts, tasks, notes. Small scale stuff which should be easy to map to a subset of an ontology

Project management
generic project management logging, simply to keep track of the tasks a developer does. I have tested this concept and it works very well, but it is a hard sell to other devs

Managing logs of solvers / AI agents
Keeping track and aggregating the large volume and complexity of any sort of solving agent logs. e.g. Which parameters gave the max result for travelling salesman problem using dataset [x], on program [y] written 2 years ago.

>  Is there a reason why you selected OpenCyc & Wordnet instead of DOLCE/DUL? 

My original thoughts was that I would need the most comprehensive and up to date ontologies and these seemed the best fit.

The reason for this was to allow any textual data to be parsed and mapped, though I am not sure this is useful in the initial stages of this project as it requires NLP as well which is out of my field and a massive time synch.

My current thinking is to have several layers of mappings, so project specific keywords can be mapped to ontology entries and use a subset on the ontology rather than the whole thing.

WordNet will be used for definitions of freeform text lookups


> Do you need to integrate Cyc facts? 

I would like to, though it is a lot of work (for devs and users) - probably outside my expertise. At a later phase perhaps.


Yes, I saw that review paper [DISI-TR-06-21] and used it as a base to help with my ontology review - it was very helpful, but from memory a some of the Ontologies were out of date / not being updated or just not public.



> What you are trying to accomplish is something like a specialized Siri

Agree - sort of like Siri for developers

**Comment by echo66** [comment]
1) It seems you want to deal with provenance and proof knowledge. For provenance, you have the [PROV model](http://www.w3.org/2011/prov/wiki/Main_Page) which is a W3C standard. For proofs, you [have the Proof Markup Language](http://inference-web.org/wiki/PML_3.0). And the best part: there is a mapping between both ontologies/models. :) For data mining, [OntoDM](http://www.ontodm.com/doku.php). For data-related vocubularies, there are some [W3C standards](http://www.w3.org/standards/techs/rdfvocabs#w3c_all)

I kind of can visualize what you want to accomplish. It seems, to me, of great interest to places like github.

2) It might be tempting to integrate knowledge from Cyc but is there any real gain? If this is a Personal Information Management system (for developers) I don't see the need to have descriptions regarding military maneuvers and equipment (Cyc has a lot of that).

3) Right now, I'm doing it manually due to the fact that Protégé has 0 ontology alignment tools...But during this weeked (or the next one), I will explore the following tool repositories:
* [Ontology Alignment Evaluation Initiative](http://oaei.ontologymatching.org/)
* [Ontology Matching](http://www.ontologymatching.org/)


--------------------

I strongly recommend that you take a look at this paper:
[Ontologies: Principles, Methods and Applications (1996)](http://citeseer.ist.psu.edu/viewdoc/download;jsessionid=014205F4F2B1204DDBCC1547E1C795A4?doi=10.1.1.111.5903&rep=rep1&type=pdf)
It is a really intuitive paper (I guess) and one of the most important papers in ontology engineering. If you have any questions regarding it, do not hesitate to ask! If you need an introdutory explanation regarding that paper, again, do not hesitate to ask! It will make very clear why you need things like competency questions in order to focus your development and evaluation.

**Comment by acutesoftware** [comment]
Thanks (again) for the useful comments and links - the OntoDM looks interesting.

Your 2nd comment made me think a lot about *why* I need to link to Cyc in the first place. I chose Cyc as it appeared to be the most comprehensive, so yes it would have many thousands of entries which would never be used. 
I still believe linking information to a robust comprehensive ontology would be 'ideal', but I am struggling to find the immediate benefit in my situation - considering the effort required. The intention was to allow a rough linking to concepts, but the application is difficult, and what exactly is the benefit to the user?

So, I will probably leave linking to the external ontologies to one side while I work on the rest of the project (lots to do still). That will give me some time to think about it.

Thanks again - and good luck with aligning the Music Ontology - the fact that you (with your history) also needed to start doing that manually, helped me decide not to pursue this here.

**Comment by echo66** [comment]
By the way, according to one of the creators of [DUL](http://www.ontologydesignpatterns.org/ont/dul/DUL.owl), Aldo Gangemi, the ontology is aligned with DBpedia 2014 (ith some imprecisions due to versioning issues, but will be fixed soon). 

Glad I could help you with some insights. :)
